version: "3.7"
services:
  app:
    image: mehdizonjy/node-hello-api
    entrypoint:
      - sh
      - "-c"
      - "node /app/app.js > /var/log/app.log"
    volumes:
      - logs-volume:/var/log
    ports:
      - 8000:3009
  fluentbit:
    image: amazon/aws-for-fluent-bit:1.3.2
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - logs-volume:/var/logs/aggregate/
      - ./fluent.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on: 
      - app

volumes:
  logs-volume:
